### ISSUE TITLE
ad block problem

### ISSUE THREAD

**Issue by yonam1** [Feodor2/Mypal#211]
Hi,
sorry for my bad English. I'm having trouble watching movies at Viki.com.  I still get the message about disabling ad block to run the movie. Sometimes the movie runs for a few minutes and then blocks again. I don't have any ad block installed. This message appears from 23/03/2020, before I had no problem watching movies on Viki.com. Is there any solution to this problem? My browser: Mypal 28.9.3(32-bit). I am not a programmer.

(Polish)
Cześć,
mam problem z oglądaniem filmów na stronie Viki.com. Ciągle wyświetla mi się komunikat o wyłączeniu adblocka, żeby uruchomić film. Czasem film uruchamia się na kilka minut, a potem znowu blokuje. Nie mam zainstalowanego żadnego adblocka. Przed 23/03/2020 komunikat o wyłączeniu adblocka się nie pojawiał. Czy można jakoś rozwiązać ten problem? Moja przeglądarka to Mypal 28.9.3 (32–bit). Proszę o proste podpowiedzi, nie jestem programistą.

P.S. Mypal is awesome. Great job. Thank You.

**Comment by kitaro1** [comment]
Zdaje się, że chodzi o założenie konta, albo zalogowanie się.
[URL=https://www.fotosik.pl/zdjecie/2c19a9086b90eb7c][IMG]https://images90.fotosik.pl/396/2c19a9086b90eb7c.png[/IMG][/URL]
Coś zmienili, chyba.

**Comment by Feodor2** [comment]
I checked in the firefox latest without adblock problem is there too. So i think about the nasty or ignorant site developers.

**Comment by yonam1** [comment]
So on Mypal I won't be able to watch movies from Viki.com? I was hoping that maybe Mypal has a built-in ad block and can be turned off. Thank you all for your reply.

**Comment by Feodor2** [comment]
Problem is solved, movie plays normally.

**Comment by yonam1** [comment]
Unfortunately it still doesn't work. I still get the message about disabling ad block to run the movie. I'm sorry to report this so late. I didn't know you were working on this problem.
