### ISSUE TITLE
Update Error v28.13.1

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#250]
Even being updated he asks to download the same version
![bug 2](https://user-images.githubusercontent.com/50956690/93689736-b7e5e200-faa7-11ea-99fd-44cff6aff70a.jpg)
![bug 1](https://user-images.githubusercontent.com/50956690/93689751-d2b85680-faa7-11ea-8157-f1a30dac660d.jpg)

**Comment by Feodor2** [comment]
Fixed bug, but who do not yet updated from 28.13.0 will have to manually update.

**Comment by SK1really** [comment]
Still the same problem, but IMHO it is a minor one.

![Mypal-Ver](https://user-images.githubusercontent.com/47065239/94111679-ac4a4080-fe44-11ea-8962-93a6203c0a5b.png) (The language pack did not cause it, btw.)

**Comment by Feodor2** [comment]
Error must gone itself.
